FROM alpine:latest as go_build
WORKDIR /app
COPY ./server ./server

# RUN apk add apt
RUN apk add go
RUN apk add build-base
ENV PATH=$PATH:/usr/local/go/bin
RUN ls > ./test.txt
RUN cd ./server && go mod download
RUN cd ./server && CGO_ENABLED=1 GOOS=linux go build main.go
# RUN cd ./server && ./main
WORKDIR /app/server
CMD ["./main"]

ENTRYPOINT ["tail", "-f", "/dev/null"]

# FROM alpine:lastest as server

# RUN apk add apt
# RUN apk add bash
# # Need to find the file path of db

# COPY --from=go_build /app/main ./server
# EXPOSE 8080

# CMD ["cd" "./server/main"]
